######################## default configuration ####################
baseURL = "/"
languageCode = "en-us"
title = "Ốc Rốt"
theme = "restaurant-hugo"
summaryLength = "10"
paginate = 4

markup.goldmark.renderer.unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
URL = "css/bootstrap.min.css"
[[params.plugins.css]]
URL = "css/slick.css"
[[params.plugins.css]]
URL = "css/font-awesome.min.css"
[[params.plugins.css]]
URL = "css/animate.min.css"
[[params.plugins.css]]
URL = "css/venobox.css"
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/responsive.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/jquery.min.js"
[[params.plugins.js]]
URL = "js/bootstrap.min.js"
[[params.plugins.js]]
URL = "js/slick.min.js"
[[params.plugins.js]]
URL = "js/wow.min.js"
[[params.plugins.js]]
URL = "js/venobox.min.js"
[[params.plugins.js]]
URL = "js/main.js"

############################## navigation ###############################

[[menu.main]]
name = "Trang chủ"
URL = "hero-area"
weight = 1

[[menu.main]]
name = "Về chúng tôi"
URL = "about-us"
weight = 2

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 3

[[menu.main]]
name = "Menu"
URL = "price"
weight = 4

[[menu.main]]
name = "Theo dõi"
URL = "subscribe"
weight = 5

[[menu.main]]
name = "Liên hệ"
URL = "contact-us"
weight = 6


#################### default parameters ################################
[params]
logo = "images/logo.png"
# meta data
author = "MiTi99"
description = "Just a developer want to become magician"
# google analitycs ID
google_analitycs_id = "Your ID"
# mainSections
main_sections = ["post"]
# copyright
copyright = "Made by [MiTi99](https://miti99.eu.org) with ❤"

# Preloader
[params.preloader]
enable = false
preloader = "" # use .png , .svg or .gif format

################################### Footer ############################
[params.footer]
enable = true
contactInfoTitle = "Thông tin <span>Liên hệ</span> "
blogTitle = "Tin <span>mới nhất</span>"
galleryTitle = "Thư viện <span>ảnh</span>"
socialTitle = "Theo dõi <span>Ốc Rốt</span>"

############################ footer contact item
[[params.footer.contactItem]]
title = "Điện thoại"
icon = "fa fa-phone"
content = "090900khôngcó"

[[params.footer.contactItem]]
title = "Địa chỉ"
icon = "fa fa-map-marker"
content = "ĐT9 - Mỹ Hạnh Nam - Đức Hoà - Long An <br> (đối diện tạp hoá Anh Tài)"

[[params.footer.contactItem]]
title = "Giờ mở cửa"
icon = "fa fa-clock"
content = "T2 - T7: 17:00 - 22:00 <br> CN: 17:00 - 21:00"

[[params.footer.contactItem]]
title = "Email"
icon = "fa fa-envelope"
content = "ocrot@gmail.com"

######################### footer gallery
[[params.footer.gallery]]
image = "images/slider-img-1.jpg"

[[params.footer.gallery]]
image = "images/slider-img-2.jpg"

[[params.footer.gallery]]
image = "images/slider-img-3.jpg"

[[params.footer.gallery]]
image = "images/slider-img-4.jpg"

[[params.footer.gallery]]
image = "images/slider-img-1.jpg"

[[params.footer.gallery]]
image = "images/slider-img-2.jpg"

######################## Social Icon 
[[params.footer.socialLink]]
icon = "facebook"
link = "https://fb.com/hoangthan1999"

[[params.footer.socialLink]]
icon = "facebook"
link = "https://fb.com/104600149239783"

[[params.footer.socialLink]]
icon = "instagram"
link = "https://fb.com/ocrot"
